<a href="https://colab.research.google.com/github/marco4u41/DarkSerieProgramacion/blob/master/practicas/Practica_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Taller de Numpy - Parte Practica

### Autor: Marco Espinosa

### Fecha: 21/04/2026


# Practica del Modulo 1

### Ejercicio 1: Crea una lista con los múltiplos de 7 entre 1 y 100 usando comprehension.


In [ ]:
# Instrucción: Usa [expresión for variable in range if condición]
Multiplos7 = [n for n in range(1, 101) if n % 7 == 0]

print(f"Múltiplos de 7: {Multiplos7}")

Múltiplos de 7: [7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]


### Ejercicio 2: Dado el diccionario datos = {'a':10, 'b':25, 'c':7, 'd':18}
###a) Crea una lista con las claves cuyo valor sea mayor a 12.
###b) Crea un nuevo diccionario con esas claves y sus valores al cuadrado

In [ ]:
datos = {'a': 10,
         'b': 25,
         'c': 7,
         'd': 18}

# a) Lista de claves con valor > 12
Claves_mayor12 = [k for k, v in datos.items() if v > 12]

# b) Diccionario con valores al cuadrado
datosCuadrado = {k: v**2 for k, v in datos.items() if v > 12}

print(f"Claves seleccionadas: {Claves_mayor12}")
print(f"Nuevo diccionario: {datosCuadrado}")

Claves seleccionadas: ['b', 'd']
Nuevo diccionario: {'b': 625, 'd': 324}


###Ejercicio 3: Define una función 'resumen(lista)' que retorne un diccionario con:
### longitud, suma, promedio, mínimo y máximo de la lista.

In [ ]:
def resumen(lista):
    if not lista:
        return "Error: No se proporcionaron datos para el análisis."

    # La función realiza el análisis dinámico de la lista
    return {
        'longitud': len(lista),
        'suma': sum(lista),
        'promedio': sum(lista) / len(lista),
        'minimo': min(lista),
        'maximo': max(lista)
    }


mis_datos =[1,2,3,8,4,5,6]

resultado = resumen(mis_datos)

print("Analisis")

if isinstance(resultado, dict):
    for clave, valor in resultado.items():

        if clave == 'promedio':
            print(f"{clave.capitalize()}: {valor:.2f}")
        else:
            print(f"{clave.capitalize()}: {valor}")

Analisis
Longitud: 7
Suma: 29
Promedio: 4.14
Minimo: 1
Maximo: 8


### Ejercicio 4: Usa map() para aplicar la función potencia(x, 3) a la lista [1,2,3,4,5].

In [ ]:

def potencia(base, exponente=2):
    return base ** exponente

numeros = [1,2,3,4,5]

cubos = list(map(lambda x: potencia(x, 3), numeros))

print(f"Originales: {numeros}")
print(f"Resultados (al cubo): {cubos}")

Originales: [1, 2, 3, 4, 5]
Resultados (al cubo): [1, 8, 27, 64, 125]


# Practica Modulo 2 - Arrays

### Ejercicio 1: Crea los siguientes arrays y verifica sus atributos (shape, dtype, ndim):

In [ ]:
import numpy as np

#a) Vector con enteros del 1 al 20.
a = np.arange(1, 21)

print("\nVector de enteros del 1 al 2o:", a)
print("shape:", a.shape, "| dtype:", a.dtype, "| ndim:", a.ndim)


Vector de enteros del 1 al 2o: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
shape: (20,) | dtype: int64 | ndim: 1


In [ ]:
import numpy as np

# b) Matriz de ceros 5x3
b = np.zeros((5, 3))


print("\nMatriz ceros:\n", b)
print("shape:", b.shape, "| dtype:", b.dtype, "| ndim:", b.ndim)


Matriz ceros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
shape: (5, 3) | dtype: float64 | ndim: 2


In [ ]:
import numpy as np

# c) 10 puntos entre -1 y 1
c = np.linspace(-1, 1, 10)

print("\nVector de valores entre -1 y 1:", c)
print("\nshape:", c.shape, "| dtype:", c.dtype, "| ndim:", c.ndim)


Vector c: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]

shape: (10,) | dtype: float64 | ndim: 1


### Ejercicio 2: Con np.random.seed(99) crea una matriz 4×4 de enteros entre 0 y 50.
### Imprime: shape, dtype, tamaño en bytes (nbytes) y el elemento [2,3].


In [ ]:
# Semilla
np.random.seed(99)

# Matriz 4x4 con enteros entre 0 y 50
matriz = np.random.randint(0, 51, (4, 4))

print("\n=== Ejercicio 2 ===")
print("Matriz:\n", matriz)

print("\nshape:", matriz.shape)
print("dtype:", matriz.dtype)
print("nbytes:", matriz.nbytes)
print("Elemento [2,3]:", matriz[2, 3])


=== Ejercicio 2 ===
Matriz:
 [[ 1 35 40  9]
 [40 18  4  5]
 [ 1 23 35 49]
 [ 1 48 29 38]]

shape: (4, 4)
dtype: int64
nbytes: 128
Elemento [2,3]: 49


### Ejercicio 3: ¿Cuál es la diferencia de dtype entre np.array([1,2,3]) y
### np.array([1.0,2.0,3.0])? Verifica con código

In [ ]:
array_int = np.array([1, 2, 3])
array_float = np.array([1.0, 2.0, 3.0])

print("\n=== Ejercicio 3 ===")
print("Array enteros:", array_int, "| dtype:", array_int.dtype)
print("Array decimales:", array_float, "| dtype:", array_float.dtype)


=== Ejercicio 3 ===
Array enteros: [1 2 3] | dtype: int64
Array decimales: [1. 2. 3.] | dtype: float64


### Ejercicio 4: Crea una matriz identidad 5×5 y verifica que la suma de su diagonal es igual a 5 (usa np.trace())

In [ ]:
identidad = np.eye(5)

print("\n=== Ejercicio 4 ===")
print("Matriz identidad:\n", identidad)

suma_diagonal = np.trace(identidad)
print("Suma de la diagonal:", suma_diagonal)


=== Ejercicio 4 ===
Matriz identidad:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Suma de la diagonal: 5.0


# Practica Modulo 3


### Ejercicio 1: Dado A = np.arange(1, 26).reshape(5, 5)
###a) Extrae la sub-matriz de las 3 últimas filas y las 3 primeras columnas.
###b) Extrae la segunda columna completa.
###c) Extrae los elementos de los ángulos (esquinas) de la matriz.

In [1]:
import numpy as np

A = np.arange(1, 26).reshape(5, 5)
print("Matriz A:\n", A)

# a) 3 últimas filas y 3 primeras columnas
sub_matriz = A[2:, :3]
print("\na) Submatriz:\n", sub_matriz)

# b) Segunda columna completa
segunda_columna = A[:, 1]
print("\nb) Segunda columna:\n", segunda_columna)

# c) Elementos de las esquinas
esquinas = [A[0,0], A[0,-1], A[-1,0], A[-1,-1]]
print("\nc) Esquinas:\n", esquinas)

Matriz A:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

a) Submatriz:
 [[11 12 13]
 [16 17 18]
 [21 22 23]]

b) Segunda columna:
 [ 2  7 12 17 22]

c) Esquinas:
 [np.int64(1), np.int64(5), np.int64(21), np.int64(25)]


###Ejercicio 2: Con la misma matriz A:
###a) Crea una máscara booleana para los valores mayores a 12.
###b) Reemplaza esos valores por -1 en una copia del array.
###c) Usa np.where para reemplazar impares por 0 y mantener los pares.

In [14]:
# a) Máscara booleana (>12)
mascara = A > 12
print("\na) Máscara:\n", mascara)

# b) Reemplazar >12 por -1 en copia
B = A.copy()
B[mascara] = -1
print("\nb) Matriz modificada:\n", B)

# c) Reemplazar impares por 0 (pares se mantienen)
C = np.where(A % 2 == 0, A, 0)
print("\nc) Pares se mantienen, impares = 0:\n", C)


a) Máscara:
 [[False False False False False]
 [False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

b) Matriz modificada:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]

c) Pares se mantienen, impares = 0:
 [[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]


###Ejercicio 3: Crea un vector de 24 elementos con arange(24).
###Reorganízalo en: (a) matriz 6×4, (b) tensor 2×3×4, (c) vector fila 1×24.

In [21]:
v = np.arange(24)
print("\nVector original:\n", v)

# a) Matriz 6x4
matriz_6x4 = v.reshape(6, 4)
print("\na) Matriz 6x4:\n", matriz_6x4)

# b) Tensor 2x3x4
tensor = v.reshape(2, 3, 4)
print("\nb) Tensor 2x3x4:\n", tensor)

# c) Vector fila 1x24
fila = v.reshape(1, 24)
print("\nc) Vector fila:\n", fila)


Vector original:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

a) Matriz 6x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

b) Tensor 2x3x4:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

c) Vector fila:
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]


### Ejercicio 4: Demuestra la diferencia vista vs. copia: modifica un elemento
###en un slice y verifica que el array original también cambia.

In [25]:
A = np.arange(1, 10).reshape(3, 3)
print("\nMatriz original:\n", A)

# Slice (vista, NO copia)
slice_A = A[0:2, 0:2]

# Modificamos el slice
slice_A[0, 0] = 999

print("\nSlice modificado:\n", slice_A)
print("\nMatriz original después del cambio:\n", A)


Matriz original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Slice modificado:
 [[999   2]
 [  4   5]]

Matriz original después del cambio:
 [[999   2   3]
 [  4   5   6]
 [  7   8   9]]


# **Practica Modulo 4**

### Ejercicio 1: Crea una matriz 5×4 de enteros aleatorios entre 1 y 100 (seed=7).
### a) Calcula la media, máximo y mínimo de cada columna.
### b) Calcula la suma acumulada de la primera fila.
### c) Normaliza la matriz para que cada columna tenga valores entre 0 y 1.
### Fórmula: (x - min_col) / (max_col - min_col)

In [47]:
import numpy as np

np.random.seed(7)
M = np.random.randint(1, 101, (5, 4))

print("Matriz:\n", M)

# a) media, max y min por columna
media = M.mean(axis=0)
maximos = M.max(axis=0)
minimos = M.min(axis=0)

print("\na) Media:", media)
print("Máximos:", maximos)
print("Mínimos:", minimos)

# b) suma acumulada de la primera fila
acum = np.cumsum(M[0])
print("\nb) Suma acumulada primera fila:", acum)

# c) normalización por columna
norm = (M - minimos) / (maximos - minimos)
print("\nc) Matriz normalizada:\n", norm.round(2))

Matriz:
 [[48 69 26 68]
 [84 24 93 58]
 [15 24 73 90]
 [43 91  9 40]
 [69 49  8 45]]

a) Media: [51.8 51.4 41.8 60.2]
Máximos: [84 91 93 90]
Mínimos: [15 24  8 40]

b) Suma acumulada primera fila: [ 48 117 143 211]

c) Matriz normalizada:
 [[0.48 0.67 0.21 0.56]
 [1.   0.   1.   0.36]
 [0.   0.   0.76 1.  ]
 [0.41 1.   0.01 0.  ]
 [0.78 0.37 0.   0.1 ]]


###Ejercicio 2: Usando broadcasting:
###a) Crea un vector fila [1,2,3,4] y un vector columna [[10],[20],[30]].
### b) Suma ambos vectores y explica el shape del resultado.

In [61]:
# a)
fila = np.array([1, 2, 3, 4])      # shape (4,)
columna = np.array([[10], [20], [30]])  # shape (3,1)

# b)
resultado = fila + columna
print("\nResultado:\n", resultado)
print("Shape:", resultado.shape)


Resultado:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
Shape: (3, 4)


###Ejercicio 3: Con el array de notas y nombres del ejemplo de argsort:
###a) ¿Cuántos estudiantes tienen nota mayor al promedio? (usa máscara booleana)
### b) Imprime solo los nombres de esos estudiantes.

In [72]:
nombres = np.array(['Carlos','Ana','Diana','Pedro','Eva','Luis'])
notas = np.array([75, 92, 88, 61, 95, 78])

# a) promedio
prom = notas.mean()
mask = notas > prom

print("\na) Promedio:", prom)
print("Cantidad mayor al promedio:", np.sum(mask))

# b) nombres de esos estudiantes
print("\nb) Estudiantes con nota mayor al promedio:")
print(nombres[mask])


a) Promedio: 81.5
Cantidad mayor al promedio: 3

b) Estudiantes con nota mayor al promedio:
['Ana' 'Diana' 'Eva']


###Ejercicio 4: Crea dos matrices 3×4 y concaténalas vertical y horizontalmente.
### Luego divide el resultado vertical en 3 partes iguales con vsplit.

In [85]:
A = np.random.randint(1, 10, (3, 4))
B = np.random.randint(1, 10, (3, 4))

print("\nMatriz A:\n", A)
print("\nMatriz B:\n", B)

# concatenación vertical
vertical = np.concatenate([A, B], axis=0)
print("\nVertical shape:", vertical.shape)

# concatenación horizontal
horizontal = np.concatenate([A, B], axis=1)
print("Horizontal shape:", horizontal.shape)

# dividir vertical en 3 partes
partes = np.vsplit(vertical, 3)

print("\nPartes:")
for i, p in enumerate(partes):
    print(f"Parte {i+1}:\n", p)


Matriz A:
 [[3 6 8 6]
 [9 6 3 1]
 [4 3 3 5]]

Matriz B:
 [[4 5 9 8]
 [1 3 8 9]
 [9 5 1 5]]

Vertical shape: (6, 4)
Horizontal shape: (3, 8)

Partes:
Parte 1:
 [[3 6 8 6]
 [9 6 3 1]]
Parte 2:
 [[4 3 3 5]
 [4 5 9 8]]
Parte 3:
 [[1 3 8 9]
 [9 5 1 5]]
